'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.8000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.CompactFramework.Design.Data generó automáticamente este código fuente, versión=2.0.50727.8000.
'
Namespace webPda
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="consultSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class consult
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://192.168.2.2:8081/web_pda3/consult.asmx"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaBD_STOCK", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaBD_STOCK() As System.Data.DataTable
            Dim results() As Object = Me.Invoke("ConsultaBD_STOCK", New Object(-1) {})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Function BeginConsultaBD_STOCK(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ConsultaBD_STOCK", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndConsultaBD_STOCK(ByVal asyncResult As System.IAsyncResult) As System.Data.DataTable
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/predios_asignados", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function predios_asignados() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("predios_asignados", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function Beginpredios_asignados(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("predios_asignados", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endpredios_asignados(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insert_reglectura", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insert_reglectura(ByVal reglectura_valor As Integer, ByVal reglectura_gps_latitud As Double, ByVal reglectura_gps_longitud As Double, ByVal idobs As Integer, ByVal reglectura_obs_detalle As String, ByVal tlectura_idtlectura As String, ByVal idusuario As Integer) As Integer
            Dim results() As Object = Me.Invoke("insert_reglectura", New Object() {reglectura_valor, reglectura_gps_latitud, reglectura_gps_longitud, idobs, reglectura_obs_detalle, tlectura_idtlectura, idusuario})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function Begininsert_reglectura(ByVal reglectura_valor As Integer, ByVal reglectura_gps_latitud As Double, ByVal reglectura_gps_longitud As Double, ByVal idobs As Integer, ByVal reglectura_obs_detalle As String, ByVal tlectura_idtlectura As String, ByVal idusuario As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("insert_reglectura", New Object() {reglectura_valor, reglectura_gps_latitud, reglectura_gps_longitud, idobs, reglectura_obs_detalle, tlectura_idtlectura, idusuario}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endinsert_reglectura(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_planilla_medidor", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function update_planilla_medidor(ByVal idcliente As Integer, ByVal idmedidor As String, ByVal idpredio As String, ByVal idlectura As String) As Integer
            Dim results() As Object = Me.Invoke("update_planilla_medidor", New Object() {idcliente, idmedidor, idpredio, idlectura})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function Beginupdate_planilla_medidor(ByVal idcliente As Integer, ByVal idmedidor As String, ByVal idpredio As String, ByVal idlectura As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("update_planilla_medidor", New Object() {idcliente, idmedidor, idpredio, idlectura}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endupdate_planilla_medidor(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_reglecturasecu", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function update_reglecturasecu(ByVal idreglectura As String, ByVal valor As Integer, ByVal idobs As Integer, ByVal observ As String, ByVal latitud_mod As Double, ByVal longitud_mod As Double) As Integer
            Dim results() As Object = Me.Invoke("update_reglecturasecu", New Object() {idreglectura, valor, idobs, observ, latitud_mod, longitud_mod})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function Beginupdate_reglecturasecu(ByVal idreglectura As String, ByVal valor As Integer, ByVal idobs As Integer, ByVal observ As String, ByVal latitud_mod As Double, ByVal longitud_mod As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("update_reglecturasecu", New Object() {idreglectura, valor, idobs, observ, latitud_mod, longitud_mod}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endupdate_reglecturasecu(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/enviar_mail2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function enviar_mail2(ByVal email_to As String, ByVal asunto As String, ByVal cliente As String, ByVal medidor As String, ByVal msgpredet As String, ByVal obs As String) As Integer
            Dim results() As Object = Me.Invoke("enviar_mail2", New Object() {email_to, asunto, cliente, medidor, msgpredet, obs})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function Beginenviar_mail2(ByVal email_to As String, ByVal asunto As String, ByVal cliente As String, ByVal medidor As String, ByVal msgpredet As String, ByVal obs As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("enviar_mail2", New Object() {email_to, asunto, cliente, medidor, msgpredet, obs}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endenviar_mail2(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/enviar_mail3", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function enviar_mail3(ByVal email_to As String, ByVal asunto As String, ByVal usuario As String, ByVal planilla As String, ByVal fp As String) As String
            Dim results() As Object = Me.Invoke("enviar_mail3", New Object() {email_to, asunto, usuario, planilla, fp})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function Beginenviar_mail3(ByVal email_to As String, ByVal asunto As String, ByVal usuario As String, ByVal planilla As String, ByVal fp As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("enviar_mail3", New Object() {email_to, asunto, usuario, planilla, fp}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endenviar_mail3(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/exportar_planilla", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function exportar_planilla() As Object
            Dim results() As Object = Me.Invoke("exportar_planilla", New Object(-1) {})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Function Beginexportar_planilla(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("exportar_planilla", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endexportar_planilla(ByVal asyncResult As System.IAsyncResult) As Object
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/convertir", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function convertir(ByVal texto As String) As Integer
            Dim results() As Object = Me.Invoke("convertir", New Object() {texto})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function Beginconvertir(ByVal texto As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("convertir", New Object() {texto}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endconvertir(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/planilla_listar_rutas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function planilla_listar_rutas(ByVal idusuario As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("planilla_listar_rutas", New Object() {idusuario})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function Beginplanilla_listar_rutas(ByVal idusuario As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("planilla_listar_rutas", New Object() {idusuario}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endplanilla_listar_rutas(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarRegistro_porCuenta", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function buscarRegistro_porCuenta(ByVal texto As String, ByVal _SQLruta As String, ByVal _SQLestadoreg As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("buscarRegistro_porCuenta", New Object() {texto, _SQLruta, _SQLestadoreg})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginbuscarRegistro_porCuenta(ByVal texto As String, ByVal _SQLruta As String, ByVal _SQLestadoreg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("buscarRegistro_porCuenta", New Object() {texto, _SQLruta, _SQLestadoreg}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndbuscarRegistro_porCuenta(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarRegistro_por", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function buscarRegistro_por(ByVal campo As String, ByVal texto As String, ByVal _SQLruta As String, ByVal _SQLestadoreg As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("buscarRegistro_por", New Object() {campo, texto, _SQLruta, _SQLestadoreg})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginbuscarRegistro_por(ByVal campo As String, ByVal texto As String, ByVal _SQLruta As String, ByVal _SQLestadoreg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("buscarRegistro_por", New Object() {campo, texto, _SQLruta, _SQLestadoreg}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndbuscarRegistro_por(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarRegistro_Manzano", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function buscarRegistro_Manzano(ByVal manzano As String, ByVal _SQLruta As String, ByVal _SQLestadoreg As String) As Integer
            Dim results() As Object = Me.Invoke("buscarRegistro_Manzano", New Object() {manzano, _SQLruta, _SQLestadoreg})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginbuscarRegistro_Manzano(ByVal manzano As String, ByVal _SQLruta As String, ByVal _SQLestadoreg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("buscarRegistro_Manzano", New Object() {manzano, _SQLruta, _SQLestadoreg}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndbuscarRegistro_Manzano(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarRegistro_LoteManzano", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function buscarRegistro_LoteManzano(ByVal manzano As String, ByVal lote As String, ByVal _SQLruta As String, ByVal _SQLestadoreg As String) As Integer
            Dim results() As Object = Me.Invoke("buscarRegistro_LoteManzano", New Object() {manzano, lote, _SQLruta, _SQLestadoreg})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginbuscarRegistro_LoteManzano(ByVal manzano As String, ByVal lote As String, ByVal _SQLruta As String, ByVal _SQLestadoreg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("buscarRegistro_LoteManzano", New Object() {manzano, lote, _SQLruta, _SQLestadoreg}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndbuscarRegistro_LoteManzano(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dame_categoriaNombre", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function dame_categoriaNombre(ByVal idcat As Integer) As String
            Dim results() As Object = Me.Invoke("dame_categoriaNombre", New Object() {idcat})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function Begindame_categoriaNombre(ByVal idcat As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("dame_categoriaNombre", New Object() {idcat}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Enddame_categoriaNombre(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/planilla_asignada_listar", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function planilla_asignada_listar(ByVal idusuario As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("planilla_asignada_listar", New Object() {idusuario})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function Beginplanilla_asignada_listar(ByVal idusuario As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("planilla_asignada_listar", New Object() {idusuario}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endplanilla_asignada_listar(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/planillaitems_min", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function planillaitems_min(ByVal idusuario As Integer, ByVal _SQLruta As String, ByVal _SQLestadoreg As String) As Integer
            Dim results() As Object = Me.Invoke("planillaitems_min", New Object() {idusuario, _SQLruta, _SQLestadoreg})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function Beginplanillaitems_min(ByVal idusuario As Integer, ByVal _SQLruta As String, ByVal _SQLestadoreg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("planillaitems_min", New Object() {idusuario, _SQLruta, _SQLestadoreg}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endplanillaitems_min(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/planillaitems_max", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function planillaitems_max(ByVal idusuario As Integer, ByVal _SQLruta As String, ByVal _SQLestadoreg As String) As Integer
            Dim results() As Object = Me.Invoke("planillaitems_max", New Object() {idusuario, _SQLruta, _SQLestadoreg})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function Beginplanillaitems_max(ByVal idusuario As Integer, ByVal _SQLruta As String, ByVal _SQLestadoreg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("planillaitems_max", New Object() {idusuario, _SQLruta, _SQLestadoreg}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endplanillaitems_max(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/planillaitems_sig", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function planillaitems_sig(ByVal idusuario As Integer, ByVal indice As Integer, ByVal _SQLruta As String, ByVal _SQLestadoreg As String) As Integer
            Dim results() As Object = Me.Invoke("planillaitems_sig", New Object() {idusuario, indice, _SQLruta, _SQLestadoreg})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function Beginplanillaitems_sig(ByVal idusuario As Integer, ByVal indice As Integer, ByVal _SQLruta As String, ByVal _SQLestadoreg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("planillaitems_sig", New Object() {idusuario, indice, _SQLruta, _SQLestadoreg}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endplanillaitems_sig(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/planillaitems_ant", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function planillaitems_ant(ByVal idusuario As Integer, ByVal indice As Integer, ByVal _SQLruta As String, ByVal _SQLestadoreg As String) As Integer
            Dim results() As Object = Me.Invoke("planillaitems_ant", New Object() {idusuario, indice, _SQLruta, _SQLestadoreg})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function Beginplanillaitems_ant(ByVal idusuario As Integer, ByVal indice As Integer, ByVal _SQLruta As String, ByVal _SQLestadoreg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("planillaitems_ant", New Object() {idusuario, indice, _SQLruta, _SQLestadoreg}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endplanillaitems_ant(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dame_secuenciaUltimoRegistro", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function dame_secuenciaUltimoRegistro(ByVal _SQLruta As String, ByVal _SQLestadoreg As String) As Integer
            Dim results() As Object = Me.Invoke("dame_secuenciaUltimoRegistro", New Object() {_SQLruta, _SQLestadoreg})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function Begindame_secuenciaUltimoRegistro(ByVal _SQLruta As String, ByVal _SQLestadoreg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("dame_secuenciaUltimoRegistro", New Object() {_SQLruta, _SQLestadoreg}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Enddame_secuenciaUltimoRegistro(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/planillaindice", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function planillaindice(ByVal _idusuario As Integer, ByVal _indice As Integer, ByVal _minsecu As Integer, ByVal _maxsecu As Integer, ByVal _indicesecu As Integer, ByVal _siguiente As Integer, ByVal _anterior As Integer, ByVal _SQLruta As String, ByVal _SQLestadoreg As String) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("planillaindice", New Object() {_idusuario, _indice, _minsecu, _maxsecu, _indicesecu, _siguiente, _anterior, _SQLruta, _SQLestadoreg})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Function Beginplanillaindice(ByVal _idusuario As Integer, ByVal _indice As Integer, ByVal _minsecu As Integer, ByVal _maxsecu As Integer, ByVal _indicesecu As Integer, ByVal _siguiente As Integer, ByVal _anterior As Integer, ByVal _SQLruta As String, ByVal _SQLestadoreg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("planillaindice", New Object() {_idusuario, _indice, _minsecu, _maxsecu, _indicesecu, _siguiente, _anterior, _SQLruta, _SQLestadoreg}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endplanillaindice(ByVal asyncResult As System.IAsyncResult) As System.Data.DataTable
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/planilla_datos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function planilla_datos(ByVal idusuario As Integer, ByVal _SQLruta As String) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("planilla_datos", New Object() {idusuario, _SQLruta})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Function Beginplanilla_datos(ByVal idusuario As Integer, ByVal _SQLruta As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("planilla_datos", New Object() {idusuario, _SQLruta}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endplanilla_datos(ByVal asyncResult As System.IAsyncResult) As System.Data.DataTable
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/planillaitem", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function planillaitem(ByVal idusuario As Integer, ByVal secu As Integer, ByVal _SQLruta As String, ByVal _SQLestadoreg As String) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("planillaitem", New Object() {idusuario, secu, _SQLruta, _SQLestadoreg})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Function Beginplanillaitem(ByVal idusuario As Integer, ByVal secu As Integer, ByVal _SQLruta As String, ByVal _SQLestadoreg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("planillaitem", New Object() {idusuario, secu, _SQLruta, _SQLestadoreg}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endplanillaitem(ByVal asyncResult As System.IAsyncResult) As System.Data.DataTable
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dame_tarifa", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function dame_tarifa(ByVal idcate As Integer, ByVal _idusuario As Integer, ByVal _SQLruta As String) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("dame_tarifa", New Object() {idcate, _idusuario, _SQLruta})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Function Begindame_tarifa(ByVal idcate As Integer, ByVal _idusuario As Integer, ByVal _SQLruta As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("dame_tarifa", New Object() {idcate, _idusuario, _SQLruta}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Enddame_tarifa(ByVal asyncResult As System.IAsyncResult) As System.Data.DataTable
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dame_obs", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function dame_obs(ByVal idobs As Integer) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("dame_obs", New Object() {idobs})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Function Begindame_obs(ByVal idobs As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("dame_obs", New Object() {idobs}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Enddame_obs(ByVal asyncResult As System.IAsyncResult) As System.Data.DataTable
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dame_sitiocaja", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function dame_sitiocaja(ByVal idsitiocaja As Integer) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("dame_sitiocaja", New Object() {idsitiocaja})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Function Begindame_sitiocaja(ByVal idsitiocaja As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("dame_sitiocaja", New Object() {idsitiocaja}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Enddame_sitiocaja(ByVal asyncResult As System.IAsyncResult) As System.Data.DataTable
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ver_avance", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ver_avance(ByVal idusuario As Integer, ByVal _SQLruta As String) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("ver_avance", New Object() {idusuario, _SQLruta})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Function Beginver_avance(ByVal idusuario As Integer, ByVal _SQLruta As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ver_avance", New Object() {idusuario, _SQLruta}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endver_avance(ByVal asyncResult As System.IAsyncResult) As System.Data.DataTable
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dame_totalitems", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function dame_totalitems(ByVal idusuario As Integer, ByVal _SQLruta As String) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("dame_totalitems", New Object() {idusuario, _SQLruta})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Function Begindame_totalitems(ByVal idusuario As Integer, ByVal _SQLruta As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("dame_totalitems", New Object() {idusuario, _SQLruta}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Enddame_totalitems(ByVal asyncResult As System.IAsyncResult) As System.Data.DataTable
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_planillaitems_reglectura", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function update_planillaitems_reglectura(ByVal indicesecu As String, ByVal idreglectura As Integer, ByVal _SQLruta As String) As Integer
            Dim results() As Object = Me.Invoke("update_planillaitems_reglectura", New Object() {indicesecu, idreglectura, _SQLruta})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function Beginupdate_planillaitems_reglectura(ByVal indicesecu As String, ByVal idreglectura As Integer, ByVal _SQLruta As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("update_planillaitems_reglectura", New Object() {indicesecu, idreglectura, _SQLruta}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endupdate_planillaitems_reglectura(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dame_registrolecturaById", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function dame_registrolecturaById(ByVal idreglectura As Integer) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("dame_registrolecturaById", New Object() {idreglectura})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Function Begindame_registrolecturaById(ByVal idreglectura As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("dame_registrolecturaById", New Object() {idreglectura}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Enddame_registrolecturaById(ByVal asyncResult As System.IAsyncResult) As System.Data.DataTable
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dame_registrolectura", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function dame_registrolectura(ByVal idusuario As Integer, ByVal secu As Integer) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("dame_registrolectura", New Object() {idusuario, secu})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Function Begindame_registrolectura(ByVal idusuario As Integer, ByVal secu As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("dame_registrolectura", New Object() {idusuario, secu}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Enddame_registrolectura(ByVal asyncResult As System.IAsyncResult) As System.Data.DataTable
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dame_tiempoLaboralRuta", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function dame_tiempoLaboralRuta(ByVal idusuario As Integer, ByVal _SQLruta As String, ByVal _SQLestadoreg As String) As String
            Dim results() As Object = Me.Invoke("dame_tiempoLaboralRuta", New Object() {idusuario, _SQLruta, _SQLestadoreg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function Begindame_tiempoLaboralRuta(ByVal idusuario As Integer, ByVal _SQLruta As String, ByVal _SQLestadoreg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("dame_tiempoLaboralRuta", New Object() {idusuario, _SQLruta, _SQLestadoreg}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Enddame_tiempoLaboralRuta(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
